# alpine installed all utilities (network, vi, wget...) 
FROM openjdk:8-jre-alpine

# ENV của dockerfile, ko phải của Linux container
ENV JAVA_FILE target/VertxWebServer.jar

# "/" = root in container linux
ENV APP_HOME /

# COPY <SRC-host> <DST-container>
COPY $JAVA_FILE $APP_HOME/app.jar

# linux commandline đứng tại WORKDIR on Container to run ENTRYPOINT
WORKDIR $APP_HOME

# cach1: after container linux starting, run ENTRYPOINT
#ENTRYPOINT ["java","-jar","app.jar"]

#cach2(hay): run bash tren linux, sau do tu bash, dung CMD to run other commands
# nếu ko khai báo mục này thì mặc định ENTRYPOINT = bash
ENTRYPOINT ["sh", "-c"]
CMD ["java -jar app.jar"]
# CMD ["java -jar app2.jar"]

# cho phép app trong container listen ở port 8080 (port ở Docker network, ko phải port HostMachine)
EXPOSE 8080

# ======================================= VOLUME ============================================
# lưu ý: trong Dockerfile của MySQL, Redis ở https://hub.docker.com/ đều khai báo VOLUME
# nếu ko chỉ định folder mount trên Host OS thì docker sẽ tự động mount tới random new folder trên Host OS
# nhiều Container có thể share chung 1 mount folder trên Host OS
# /data/vol1: folder in container linux
VOLUME /data/vol1
#VOLUME /data/vol1 /data/vol2